
/*
 * Automatically generated by Magic.
 */
create table requests(
  request_id integer not null primary key autoincrement,
  ts text not null,
  text text not null,
  external_id text
);

create table replies(
  reply_id integer not null primary key autoincrement,
  request_id INTEGER not null references requests(request_id),
  text text not null
);
